### PR TITLE
Effect manager

### PR DESCRIPTION
**Pull request by chesterhow**
Here's my implementation of how to manage cross-entity comms. Let me know what you guys think. 

If you're a little confused here's an example of how `entityEffects` would look like
```c++
std::unordered_map<int, std::unordered_map<effectNS::EFFECT_TYPE, float>> entityEffects = {
  { 0, { { effectNS::ENLARGE, 1.0f }, { effectNS::INVERT, 0.2f } } },
  { 1, { { effectNS::MAGNET, 2.4f } } }
};

// Outer unordered_map
// Key: Entity ID
// Value: inner unordered_map

// Inner unordered_map
// Key: effect enum
// Value: Remaining duration for that effect
```

Don't have to merge this yet. I'm just showing how I did it. Open to suggestions or better implementations.

### CODE REVIEW

**Comment by elcoms** [comment]
- What's the use of the outer map?
- What do you need id for, aren't they all the same? 
- If you put them inside the entity class as variables, they would each have their id and duration, isn't it?

**Comment by chesterhow** [comment]
@elcoms Someone too free. 
- Outer map stores entityId as the key and the inner map as the value. So its a id to currentEffects map
- Entity Id is unique
- Not sure what you're asking. All entities have a unique id and only pickups store the duration

**Comment by elcoms** [comment]
@chesterhow I was on a bus.

- I understand that, but why? What is it needed?
- Yes, they are unique. What are they needed?
- Are the maps inside `pongstar.cpp` or their own class (i.e. `paddle.cpp`)?

**Comment by chesterhow** [comment]
@elcoms 
- To answer questions 1 and 3: There is only 1 main map which is stored in EffectManager. This is our main source of truth and it lists all the current effects all entities have at the moment. It also decrements the time left of each effect. All entities use this map to check their current effects
- To tell the difference between 2 same entities. E.g. 2 paddles

Good day lad.

**Pull request merged**
